name: admin

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  run-azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'azure cli login'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ADMIN_CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: 'run az commands'
        run: |
          az account list -o table
          az group list -o table
          az aks list -o table
          aksname=$(az aks list --query "[].name" -o tsv)
          aksresourceGroup=$(az aks list --query "[].resourceGroup" -o tsv)
          az aks get-credentials -n $aksname -g $aksresourceGroup
          sudo az aks install-cli
          kubelogin convert-kubeconfig -l azurecli
          az aks command invoke -n $aksname -g $aksresourceGroup -c 'kubectl get pods -A'
          az aks command invoke -n $aksname -g $aksresourceGroup -f deployment.yaml -c 'kubectl apply -f deployment.yaml'
          az aks command invoke -n $aksname -g $aksresourceGroup -f namespaces.yaml -c 'kubectl apply -f namespaces.yaml'
         

          

      - name: printenv
        run: |
          printenv|sort
