name: azlogin

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  run-azlogin:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account list -o table
          az group list -o table
      - name: printenv
        run: |
          printenv
