name: test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  run-blank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - name: printenv
        run: |
          printenv
