name: developer

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  run-azlogin:
    runs-on: ubuntu-latest
    steps:
      - name: 'azure cli login'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.DEVELOPER_CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}

      - name: 'run az commands'
        run: |
          az account list -o table
          az group list -o table
          az aks list -o table
          aksname=$(az aks list --query "[].name" -o tsv)
          aksresourceGroup=$(az aks list --query "[].resourceGroup" -o tsv)
          az aks get-credentials -n $aksname -g $aksresourceGroup
          sudo az aks install-cli
          kubelogin convert-kubeconfig -l azurecli
          az aks command invoke -n $aksname -g $aksresourceGroup 'kubectl pods -A'
          az aks command invoke -n $aksname -g $aksresourceGroup 'kubectl run nginx --image=nginx'
      
      - name: printenv
        run: |
          printenv|sort
