name: terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: printenv
        run: |
          printenv|sort
      - name: terraform init
        run: |
          terraform -chdir=infra init \
              -backend-config="key=secureaks.tfstate" \
              -backend-config="resource_group_name=${{ vars.STATE_RESOURCE_GROUP_NAME }}" \
              -backend-config="storage_account_name=${{ vars.STATE_STORAGE_ACCOUNT_NAME }}" \
      - name: terraform plan 
        run: |
          terraform -chdir=infra plan -var="resource_group_name=rgplatform${{ vars.ENV_ID }}"
      - name: terraform apply 
        run: |
          terraform -chdir=infra apply -auto-approve -var="resource_group_name=rgplatform${{ vars.ENV_ID }}"


