name: terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: printenv
        run: |
          printenv
          echo "-----"
          printenv|grep ARM
      - name: terraform init
        run: |
          terraform -chdir=infra init \
              -backend-config="key=secureaks.tfstate" \
              -backend-config="resource_group_name=rg101125" \
              -backend-config="storage_account_name=sa101125" \
              -backend-config="use_oidc=true"
      - name: terraform plan
        run: |
          terraform -chdir=infra plan 

              

